-- 사용자(USER04/PWD) 생성하기
CREATE USER USER04 IDENTIFIED BY PWD;

-- ROLE 부여
GRANT CONNECT, RESOURCE TO USER04; -- 로그인가능, 테이블 생성등 여러 권한 부여해줌

-- 사용자 롤 정의
CREATE ROLE MROLE;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO MROLE;

CREATE USER USER05 IDENTIFIED BY PWD;
GRANT MROLE TO USER05;
REVOKE MROLE FROM USER05;

-- 동의어 생성 및 제거
DROP TABLE SYSTBL;
CREATE TABLE SYSTBL(
        ENAME VARCHAR2(20)
);
INSERT INTO SYSTBL VALUES('쏘연');
SELECT * FROM SYSTBL;

-- 객체 권한 부여
GRANT SELECT ON SYSTBL TO SCOTT; -- SYSTBL권한을 SCOTT에게 부여
GRANT CREATE SYNONYM TO SCOTT; -- SCOTT에게 동의어 부여권 줌