SELECT * FROM EMP;

-- SEQUENCE 생성
CREATE SEQUENCE DEPT_DEPTNO_SQ
INCREMENT BY 10
START WITH 10;

-- SEQUENCE 조회
DESC USER_SEQUENCES;
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG
FROM USER_SEQUENCES;

-- SEQUENCE값 확인 : CURRVAL, NEXTVAL
SELECT DEPT_DEPTNO_SQ.NEXTVAL FROM DUAL; -- 10씩 증가함
SELECT DEPT_DEPTNO_SQ.CURRVAL FROM DUAL; -- 현재 값(마지막으로 생성된 시퀀스)을 보여줌

--SEQUENCE 실무
CREATE SEQUENCE EMP_SEQ
START WITH 1 -- 1부터 시작
INCREMENT BY 1 -- 1씩 증가
MAXVALUE 100000; -- 최대 100000까지

DROP TABLE EMP01;
CREATE TABLE EMP01(
        EMPNO NUMBER(4) PRIMARY KEY,
        -- ENAME VARCHAR2(10), 오라클 문자열 자료형
        ENAME VARCHAR(10), -- ANSI 문자열 자료형, VARCHAR = VARCHAR2
        HIREDATE DATE
);     

INSERT INTO EMP01 VALUES(EMP_SEQ.NEXTVAL, 'ZAO', SYSDATE);
INSERT INTO EMP01 VALUES(EMP_SEQ.NEXTVAL, 'LEE', SYSDATE+1);
-- 이런식으로 시퀀스를 만들어 놓으면 차례대로 들어가개됨 개꿀
SELECT * FROM EMP01;

-- SEQUENCE 삭제
SELECT SEQUENCE_NAME, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG
FROM USER_SEQUENCES; -- 시퀀스 뭐가 있는지 볼수 있음

DROP SEQUENCE DEPT_DEPTNO_SQ; -- 삭제시킴

-- SEQUENCE 수정
ALTER SEQUENCE EMP_SEQ
MAXVALUE 100; -- 기존 최대 100000까지 들어갈수 있었는데 100으로 바꿔버림 

-- 1. 최소값 1, 최대값 99999999, 1000부터 시작해서 1씩 증가하는 ORDERS_SEQ 라는 시퀀스를 만들어보자.
CREATE SEQUENCE ORDERS_SEQ
MINVALUE 1
MAXVALUE 99999999
INCREMENT BY 1
START WITH 1000;

SELECT ORDERS_SEQ.NEXTVAL FROM DUAL;
SELECT ORDERS_SEQ.CURRVAL FROM DUAL;

-- 인덱스 정보 조회
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN ('EMP', 'DEPT');

-- 조회 속도 비교
-- 인덱스가 아닌 컬럼으로 검색하기
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT * FROM EMP;
SELECT * FROM EMP01;
DESC EMP01;

SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN('EMP', 'EMP01');

INSERT INTO EMP01 
SELECT * FROM EMP01;

SELECT COUNT(*) FROM EMP01;

INSERT INTO EMP01(EMPNO, ENAME) VALUES (1111, 'ZAO');

SET TIME ON 
SELECT DISTINCT EMPNO, ENAME
FROM EMP01
WHERE ENAME = 'ZAO';

-- 인덱스 설정하기
CREATE INDEX IDX_EMP01_ENAME
ON EMP01(ENAME);

-- 인덱스 제거하기
DROP INDEX IDX_EMP01_ENAME;


