SHOW USER;

-- 객체 권한 부여
GRANT SELECT ON EMP TO USER01; 

SELECT * FROM SCOTT.EMP;
SELECT * FROM EMP;

SELECT * FROM USER_TAB_PRIVS_MADE; -- 자신이 부여한 객체권한
SELECT * FROM USER_TAB_PRIVS_RECD; -- 자신이 받은 객체권한

-- 객체 권한 제거
REVOKE SELECT ON EMP FROM USER01;

-- WITH GRANT OPTION
GRANT SELECT ON SCOTT.EMP TO USER02
WITH GRANT OPTION;