-- 시스템권한(SYSTEM PRIVILEGES)
-- 사용자 생성 : CREATE USER
CREATE USER USER10 IDENTIFIED BY USER10; -- IDENTIFIED BY USER10 : 비밀번호인거

-- 사용자 비밀번호 변경
ALTER USER USER10 IDENTIFIED BY PWD; 

-- 권한을 부여하기 : GRANT
GRANT CREATE SESSION TO USER10; -- 권한 부여해야 CMD에서 들어갈 수 있음
GRANT CREATE TABLE TO USER10; -- TABLE 생성할 수 있는 권한 부여 
-- ORA-01950: no privileges on tablespace 'SYSTEM' 인경우
GRANT UNLIMITED TABLESPACE TO USER10; -- 모든 테이블 스페이스에 할당량을 줄 수 있는 권한

-- 테이블 스페이스 확인하기
SELECT USERNAME, DEFAULT_TABLESPACE
FROM DBA_USERS
WHERE USERNAME IN('USER10', 'SCOTT');

-- 테이블 스페이스 변경하기
ALTER USER USER10 DEFAULT TABLESPACE USERS;
ALTER USER USER10 TEMPORARY TABLESPACE TEMP;

-- 테이블 스페이스 쿼터 할당하기
ALTER USER USER10 
QUOTA 1000M ON USERS;

-- WITH ADMIN OPTOIN
CREATE USER USER02 IDENTIFIED BY TIGERL;
ALTER USER USER02 IDENTIFIED BY TIGER; 
GRANT CREATE SESSION TO USER02 WITH ADMIN OPTION; -- CREATE SESSION 권한의 DBA 관리자 권한 부여

CREATE USER USER03 IDENTIFIED BY TIGER;
GRANT CREATE SESSION TO USER03;

CREATE USER USER01 IDENTIFIED BY TIGER;
